
export const STARWARS_GET_PEOPLE = 'STARWARS_GET_PEOPLE';
export const STARWARS_LOADED_PEOPLE = 'STARWARS_LOADED_PEOPLE';
export const STARWARS_GET_DETAILS = 'STARWARS_GET_DETAILS';
export const STARWARS_LOADED_DETAILS = 'STARWARS_LOADED_DETAILS';
export const STARWARS_LOADED_FAIL = 'STARWARS_LOADED_FAIL';
